fix: update migration entry points
ngxtension/ngxtension-platform pull request #448
Opened 2024-07-14 04:26 UTC by jdegand

Closes #447.

2024-07-15 12:55 UTC, nartc approved these changes

2024-07-15 12:57 UTC, nartc requested changes
Actually, this wasn't the cause. Check the `PageTitle` component and update the `sourceCodeUrl` there.

2024-07-15 17:03 UTC, jdegand commented
Change this `https://github.com/nartc/ngxtension-platform/tree/main/libs/ngxtension/${entryPoint}` to `https://github.com/nartc/ngxtension-platform/tree/main/libs/${entryPoint}` and add folder to all other entry points ?

I think `bundleJsUrl` will also have to be updated as well from `https://deno.bundlejs.com?q=ngxtension/${entryPoint}&treeshake=` to `https://deno.bundlejs.com?q=${entryPoint}&treeshake=`.

2024-07-15 17:26 UTC, nartc commented
@jdegand 
- Change `https://github.com/nartc/ngxtension-platform/tree/main/libs/ngxtension/${entryPoint}` to `https://github.com/ngxtension/ngxtension-platform/tree/main/libs/ngxtension/${entryPoint}`
- The `bundleJsUrl` is fine because it reaches out to npmjs instead of repo's file structure.

2024-07-15 17:40 UTC, jdegand commented
I don't this will work `https://github.com/ngxtension/ngxtension-platform/tree/main/libs/ngxtension/${entryPoint}` because the migration files are not inside the libs/ngxtension file.  They are inside the plugin folder.  

Other issues I noticed: `Gesture` vs `Gestures` file mismatch, `if-validator` does not have a readme file.

2024-07-15 21:39 UTC, nartc commented on docs/src/components/PageTitle.astro
> +const sourceCodeUrl = `https://github.com/nartc/ngxtension-platform/tree/main/libs/${entryPoint}`;
```suggestion
const sourceCodeUrl = `https://github.com/ngxtension/ngxtension-platform/tree/main/libs/${entryPoint}`;
```

2024-07-15 21:39 UTC, nartc commented
@jdegand as for missing readme files, I'd like a separate PR if possible. Thanks!!

2024-08-02 14:39 UTC, nartc approved these changes

2024-08-02 14:39 UTC, merged